### PR TITLE
Remove makefile check, replace by rlCheckRecommended and rlCheckRequired

### PR DESCRIPTION
**Pull request by Koncpa**

### CODE REVIEW

**Comment by comps** [comment]
@Koncpa Why the explicit `rlImport`s? ... Why can't `--all` import it?

**Comment by comps** [comment]
Ah, the commit message mentions
```
Due adding basic rsyslog library to main.fmf require field
import failed. Need to explicitly specify import
of basic rsyslog lib for proper importing of lib.
```
I guess `rlImport` could be extended to read `main.fmf`, but that may be out of scope.

**Comment by Koncpa** [comment]
It occured after specifying rsyslog lib in `main.fmf`.

**Comment by sopos** [comment]
> Because, when was used `rlImport --all`, the rsyslog lib isn't correctly imported, so I explicitly import it.

The support is there for quite a long time already. The first attempt to make it compatible was https://github.com/beakerlib/beakerlib/commit/a36cb5287bb4ae8439ec6b19190eedc5aa60482c

If it does not work it might be either wrong usage or a bug.

**Comment by Koncpa** [comment]
> > Because, when was used `rlImport --all`, the rsyslog lib isn't correctly imported, so I explicitly import it.
> 
> The support is there for quite a long time already. The first attempt to make it compatible was [beakerlib/beakerlib@a36cb52](https://github.com/beakerlib/beakerlib/commit/a36cb5287bb4ae8439ec6b19190eedc5aa60482c)
> 
> If it does not work it might be either wrong usage or a bug.

Do you have proposal of any other working solution? Otherwise I'm for importing rsyslog lib explicitly, for now it's most easier workaround and also it can improve help readability of code to se what's really imported.

**Comment by sopos** [comment]
Well, the issue was missing `framework: beakerlib` in this repo fmf metadata. I spend some significant time on it as well. Now it should work.

**Comment by Koncpa** [comment]
@sopos Previous commit related to `rlImport`  removed and also removed makefilecheck commit adjusted with you proposed changes..

**Review by sopos — APPROVED** [review]

**Pull request merged**
